#pragma once

enum PAGETYPE {PG_CONFIG=0, PG_INPUT, PG_SOUND, PG_DISK, PG_ADVANCED, PG_NUM_SHEETS};
enum UICONTROLSTATE {UI_UNDEFINED, UI_DISABLE, UI_ENABLE};
enum CARDSTATE {CARD_UNCHANGED, CARD_UNPLUGGED, CARD_INSERTED};
