;--------------------------------------
CH				 = $24					; CURSOR HORIZONTAL
CV				 = $25					; CURSOR VERTICAL

BASL			 = $28					; TEXT BASE LOW
BASH			 = $29					; TEXT BASE HIGH

INVFLG			 = $32					; NORMAL/INVERSE /FLASH (FF,7F,3F)
;--------------------------------------
MON_POWERUP		 = $3F2
MON_POWERUPBYTE	 = $3F4
;--------------------------------------
MON_SLOOP		 = $FABA
MON_SETTXT		 = $FB39
MON_HOME		 = $FC58
MON_VTABA		 = $FC24
MON_CR			 = $FC62
MON_CROUT		 = $FD8E
MON_PRBYTE		 = $FDDA
MON_COUT		 = $FDED
MON_INVERSE		 = $FE80
MON_NORM		 = $FE84
MON_IN0			 = $FE89
MON_PR0			 = $FE93
MON_RTS			 = $FF58
;--------------------------------------
