#pragma once

#define NIBBLES_PER_TRACK_NIB 0x1A00
#define NIBBLES_PER_TRACK_WOZ2 0x1A18	// 6680
#define NIBBLES_PER_TRACK NIBBLES_PER_TRACK_WOZ2	// MAX(NIBBLES_PER_TRACK_NIB, NIBBLES_PER_TRACK_WOZ2)

const UINT NUM_SECTORS = 16;
